### ISSUE TITLE
Find out how to get HTML to transition in the same as surrounding passage text

### ISSUE THREAD

**Issue by whymog** [whymog/efjm#15]

**Comment by whymog** [comment]
This is especially a problem in the mom's tent - note sequence. I'll see if I can fix that now.

**Comment by whymog** [comment]
Went through and swept for occurrences of this in https://github.com/whymog/efjm/pull/33. Closing this out.

**Comment by whymog** [comment]
This is still busted in Chrome, but working fine in Firefox. We should take another look.

**Comment by catdad666** [comment]
Resolving this after merging #43
