### ISSUE TITLE
Final Review Punch List

### ISSUE THREAD

**Issue by whymog** [whymog/efjm#20]
This issue will collect all the tiny things we ought to check and refine before shipping the game. I'll just update this as we go.

- Action prompts:
    - Do all actions have a `>` preceding them?
    - Do they consistently either have one `>` or two `>>`? Pick one style and apply it to the whole game. (see [comment](https://github.com/whymog/efjm/pull/18/files#r212828949))
    - Is there a space after each `>`/`>>` prompt? Decide whether or not to include the space and apply it consistently to the whole game.
- Grammar and syntax:
    - Are em-dashes consistently used? Are they offset by spaces or not? We should ensure consistency throughout. (**EDIT:** Done.)
- Proper nouns:
    - "Jaysus" — are there any uses with a hyphen? (**EDIT:** Nope! We're good.)
    - "Tent City"/"the Tents" - Are these used consistently? (**EDIT:** Yep!)
    - "Gatherville" - Is it always referred to as "Gatherville"? In some earlier docs we called it "The Gather" — make sure those references are gone. (**EDIT:** Mmhmm. We're good.)
- Visual effects:
    - When a new passage gets displayed inline, do we consistently apply the transition effect to fade in from black? (**EDIT:** Yes, this was largely fixed in a separate issue.)

**Comment by catdad666** [comment]
- Outfit
  - Does every description of the character's clothes match the t-shirt/jeans established in the opening?
- Letter design
  - Does every letter in the game display and look the same?
- Punctuation in links
  - Do all links at the end of sentences include punctuation outside the link?

**Comment by catdad666** [comment]
Resolved in #69 (nice)
