### ISSUE TITLE
Add flashback to Roach Market

### ISSUE THREAD

**Issue by catdad666** [whymog/efjm#28]
I noticed that I had this in the #fragments channel in Discord, but never added it to the script. There's one last flashback, the finale one in this doc, that I'd like in the game:

https://docs.google.com/document/d/1L1i6Qyo0ULkpMrjMA2qUpwY0jGnEkyOCQi3C4KbkJgU/edit

I'd like it to go in the Roach Market, maybe somewhere in the Junk Heap, to give the player more of an idea of who Leo is and why he'd be chasing after you. Open to all thoughts, even if it's just "We don't actually need this."

**Comment by whymog** [comment]
I left a lot of suggestions, but don't panic — I think it's a good scene that would add some valuable context to the game. I think it should probably be optional, though — it's a bit of a departure in tone from the rest of the game, and it might be kind of nice to tuck away as a memory triggered by something in the junk heap. (Potentially it could only trigger on your first exit from the junk pile if you examine 3+ items.) Thoughts?

**Comment by catdad666** [comment]
@whymog Great idea on how to trigger! I definitely like the context it adds to the game, but I think I let the personal, first-draft style get away from me. Thanks for the perceptive, honest edit! Working on how to get this into the RM now.

**Comment by catdad666** [comment]
This is in #49
