### ISSUE TITLE
Give Darryl a heavier hint about going to get a game for Toe

### ISSUE THREAD

**Issue by whymog** [whymog/efjm#31]
Let's write a line or two to give Darryl more of a purpose on this barren earth.

**Comment by whymog** [comment]
On playing through this again today, I didn't actually feel like this was all that unclear. It did require me to connect the dots, but even just using trial-and-error here wouldn't be too challenging. In other words, I think I'm good with playtesting it as-is and seeing if people get lost.

**Comment by catdad666** [comment]
Now that we know people can get lost here, I'd suggest adding more text in three places:
* First encounter with Auntie (description of games in her shop)
* Clearer hint from Darryl about games being at Auntie's Shop
* Clearer prompt when Toe won't speak to you (maybe he's bored or he looks at an empty shelf labeled "Games" or something)

**Comment by catdad666** [comment]
This is in #48
