### ISSUE TITLE
CSS is way uggo

### ISSUE THREAD

**Issue by whymog** [whymog/efjm#4]
We should really, really stop using the default styles for Harlowe2.

**Comment by whymog** [comment]
Another thing to watch for: mobile styles. The padding is real nasty on my iPhone. We should cut it way down. Probably just use a simple `@media` query to take care of that.

**Comment by catdad666** [comment]
Merriweather is a good Google Font option. Consider Adobe Caslon if we want to hook up Nathan's Typekit account.

Would like to demo what a classic, computer green font would look like for links to improve readability.

**Comment by whymog** [comment]
I'm really glad we're thinking about readability and accessibility. A few things I'll say from the little bit of accessibility knowledge I have:

- Serif fonts are more readable than sans-serif fonts in large blocks of prose.
- Green on black will be higher contrast than blue on black, but dark green quickly gets as murky as blue. If we're gonna go this route, we'll likely need to make our links very bright green. Like a Surge color of green. And I'm not sure if that's a good idea.
- There exist all kinds of OS- and browser-level accessibility features intended to parse text, like increasing contrast, enforcing monochrome, etc. I'm not sure this is something we ought to be overly concerned with at this point because it's easy for people to fix this on their end depending on their needs.
- I have a sneaking suspicion that the real accessibility problem is Harlowe. It wraps text in very strange ways and the way it conjures up new prose sections might be really jarring. I think in the future we should consider rolling our own theme if we choose to stick with Twine.

**Comment by catdad666** [comment]
All good points!
* Definitely into a serif font like Merriweather
* I agree that Harlowe is an accessibility issue by itself and some of the text effects are inaccessible by screen readers.
* I'm down to see what surge green links look like tbh. I think it will probably look a little funky and I'm (maybe naively) hoping it will match the tone of the game.

**Comment by catdad666** [comment]
Resolved in #66
