### ISSUE TITLE
Add spooky font to the death scenes

### ISSUE THREAD

**Issue by catdad666** [whymog/efjm#44]
Nathan suggested this in my first Gutter PR. Would love to see a dumb font applied to these scenes to make them stand out even a bit more. Open to any and all thoughts!

Did some very quick searching and I think something handwriting-ish, but legible like this would work: https://fonts.google.com/specimen/Caveat .

**Comment by whymog** [comment]
Hah, that could be kinda fun. :)

**Comment by catdad666** [comment]
Would rather work on feedback and pacing than this. I also think we can cool it with text effects. I still think this is a cool idea, but I'm killing it in favor of keeping the issues list reasonable.
