### ISSUE TITLE
Create convention for naming passages

### ISSUE THREAD

**Issue by thenthdegree** [whymog/efjm#6]
I.e., do we want to do passage names that use spaces? Dashes in place of spaces? No spaces, all passage names in camelCase? Etc.

**Comment by thenthdegree** [comment]
(My personal pref would probably be to avoid use of spaces in passage names, in whatever way works best for others!)

**Comment by whymog** [comment]
I prefer spaces with dashes. They're just variable names, but they almost always appear in prose, or near it, so it reads cleaner to me. The less code-y we can have them, the better, in my opinion!

**Comment by whymog** [comment]
The convention I've been following is:

`Capitalized Broader Area - More specific area in sentence case (Condition, like "lit" or "nighttime")`

**Comment by whymog** [comment]
@catdad666, whatchu thinkin'

**Comment by catdad666** [comment]
@whymog @thenthdegree I've been using spaces and no dashes (i.e. "Mom's Tent intro" or "Mom's Tent den"). I agree that I'd like to keep it more prose-ish. I was using numbers and letters in my Google Docs and it was just so easy to get lost, so anything but that.

I agree with @whymog 's suggestion of 

> Capitalized Broader Area - More specific area

but I have a few suggested tweaks based on how I've needed to name stuff. I sometimes like to split locations with lots of text between passages, so I'll add a # if it's the same location/chain of text. I also sometimes name passages by the choice that triggered it ("Mom's Tent faygo") for branching narrative stuff. So, my pitch is basically:

> Name of section - Brief passage description (# if appropriate)

How do y'all feel about numbers and naming based on choice when it makes sense?

**Comment by thenthdegree** [comment]
The thing I've run into re: passage names that look more similar to prose is that sometimes it seems the syntax highlighting in Atom isn't 100%, for some Harlowe passage links:

<img width="755" alt="screen shot 2018-08-12 at 10 43 38 pm" src="https://user-images.githubusercontent.com/38260783/44014525-4c98e1ca-9e81-11e8-9dbf-0caab8bb5d9d.png">

Having passage names that look a little less like prose could be helpful in cases like this, when the syntax highlighter seems to get confused.

**Comment by whymog** [comment]
Hey, just checking in here — is this still something that ought to warrant action, or are things in a good place?

**Comment by catdad666** [comment]
I think it's fine honestly. The game is mostly built and I just check the passage name before I paste it in. It's definitely a little messy that standards vary between sections based on who built it, but I would put this at a low priority if we even address it at all.

**Comment by whymog** [comment]
@thenthdegree I'd say this is up to you — if you'd like to revisit this, we can keep it open. If not, feel free to close!

**Comment by whymog** [comment]
Closing since it seems like this is inactive, but feel free to reopen!
